build:
  cargo build
lint:
  cargo clippy --lib
release:
  cargo --lib
run:
  cargo run
sweep:
  cargo sweep -s -v
  cargo build
  cargo build --release
  cargo test
  cargo sweep -f -v
test:
  cargo test
coverage:
  cargo llvm-cov --all-features --lcov --ignore-filename-regex tests --output-path coverage/lcov.info
watch:
  cargo watch --clear --postpone -x 'clippy --lib' -x 'test --lib -- --show-output' -x 'run'
tcp_plug:
  cargo run --package tcp-plug-socket --example tcp_plugsocket_imitator
tcp_command_sender:
  cargo run --package tcp-plug-socket --example simple_command_sender
