@host = http://localhost:3000

### <h1>Smarthome web server</h1>
GET {{host}}/

### 200 OK
GET {{host}}/health_check

@api = {{host}}/api

### /locations
### GET list all location
GET {{api}}/locations

### POST create location
POST {{api}}/locations
Content-Type: application/json

{
    "name": "Some random loc"
}

### uuid from prev request
@test_loc_uuid = d210b03d-0a6a-4049-bf40-dc25bdc6af99

### /locations/:loc_id
### GET read location
GET {{api}}/locations/{{test_loc_uuid}}

### POST update location
PUT {{api}}/locations/{{test_loc_uuid}}
Content-Type: application/json

{
    "name": "Renamed location"
}

### DELETE delete location
DELETE {{api}}/locations/{{test_loc_uuid}}

### /locations/:loc_id/rooms
### GET list all rooms for :loc_id
GET {{api}}/locations/{{test_loc_uuid}}/rooms

### POST create room for :loc_id
POST {{api}}/locations/{{test_loc_uuid}}/rooms
Content-Type: application/json

{
    "name": "Room 42"
}

@test_room_uuid = 958741f0-4a1b-42b9-b81d-a2fdd2a5350e

### /rooms/:room_id
### GET read room
GET {{api}}/rooms/{{test_room_uuid}}

### POST update room
PUT {{api}}/rooms/{{test_room_uuid}}
Content-Type: application/json

{
    "name": "Room 33"
}

### DELETE delete room
DELETE {{api}}/rooms/{{test_room_uuid}}

### /rooms/:room_id/devices
### GET list all devices for :room_id
GET {{api}}/rooms/{{test_room_uuid}}/devices

### POST create device for :room_id
POST {{api}}/rooms/{{test_room_uuid}}/devices
Content-Type: application/json

{
    "name": "Device 13"
}

@test_device_uuid = 58a708be-8d6d-4992-adc2-ded466a5fb82

### /devices/:dev_id
### GET read :dev_id
GET {{api}}/devices/{{test_device_uuid}}

### POST update :dev_id
PUT {{api}}/devices/{{test_device_uuid}}
Content-Type: application/json

{
    "name": "Device 33"
}

### DELETE delete
DELETE {{api}}/devices/{{test_device_uuid}}
